import React,  { Component }  from 'react';
import '../App.css';
import './css/Nav.css';
import { NavLink } from 'react-router-dom';


/* ===============================================================================================================
This is a static header that sits above the other components of the app and contains the main navigation bar. 
It also displays the app title/logo and the username and ID of the logged-in user. The links of the navigation bar 
link to the BrowserRouter enabled components of the app. The router links are passed in from App.js as props.
=================================================================================================================*/
class Nav extends Component {

  constructor(props) {
    super(props);
  }


  render() {

    var links = this.props.navLinks;     // Array containing names of the nav links.
    var routes = this.props.appRoutes;  // Routes (a JS object) generated by App.js. 

    // Iterating through link names and creating an array of 'NavLink's. i.e., one for each route.
    const navLinks = links.map((name, idx)=>{
           var link = (<NavLink to = {routes[name].url} key = {idx} exact={true} className = "nav-link" activeStyle = {{backgroundColor:'orange', color:'black'}}>{name} </NavLink>)
           return link;
    })

    // Code to display the user's name and ID.
    var userMsg = (<div style = {{marginRight:'240px'}}></div>);
    var user = this.props.user;
    if (user != null){
         userMsg = (<div style = {{textAlign:'left'}}>
                          <p>Logged in as: <b>{user.username}</b></p>
                          <p>User ID: {user.userId}</p>
                    </div>)
    }
   
    // Rendering the content.
    return(
      <div className = "nav">
      <h3 className = "title">Predictive Maintenance</h3>
      <div id = "navLinks" className = "nav-links">
        {navLinks}
      </div>
      <div style = {{marginRight:'80px'}}>{userMsg}</div>
      </div>
    );
    }

  }
 

  export default Nav;