FROM tiangolo/meinheld-gunicorn:python3.8 
WORKDIR /app
RUN pip install flask
RUN pip install python-benedict
RUN pip install scikit-learn
RUN pip install requests
RUN pip install flask_mqtt
RUN pip install paho-mqtt
RUN pip install flask-cors
RUN pip install pandas
RUN pip install numpy
RUN pip install pymongo
COPY . /app



